name: 🔨Build AdGuard DNS filter

on:
  push:
    branches:
      - master
  schedule:
    - cron: '17 19 * * *' # Every day

jobs:
  build:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: yarn
        run: |
          yarn install

      - name: Compile
        run: |
          TLS=insecure node index.js

      - name: Build DNS Filter
        run: |
          yarn run build-ios
          yarn run build-android

      - name: prepare deploy
        run: |
          mkdir -p build
          cp -rf Filters build/
        env:
          CI: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
